export interface Product {
  id: number;
  name: string;
  price: number;
  image: string;
  mainCategory: "womens" | "mens" | "kids" | "accessories" | "shoes" | "jewelry";
  subCategories?: string[];
  description?: string;
  isNew?: boolean;
  isBestseller?: boolean;
  rating?: number;
  reviews?: number;
  size?: string;
  colors?: string[];
  images?: string[];
  inStock?: boolean;
  stock?: number;
  isFeatured?: boolean;
}

export interface ProductFilters {
  categories: string[];
  priceRange: [number, number];
  minRating?: number;
  inStock?: boolean;
  tags?: string[];
}

export interface ProductSort {
  field: 'featured' | 'newest' | 'price' | 'rating' | 'name';
  order: 'asc' | 'desc';
}

export const mockProducts: Product[] = [
  // Women's Collection
  {
    id: 1,
    name: "Cashmere Wrap Coat",
    price: 2899,
    image: "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=800",
    mainCategory: "womens",
    subCategories: ["outerwear", "coats"],
    description: "Luxurious 100% cashmere wrap coat with belted waist. Timelessly elegant and supremely soft.",
    isNew: true,
    isBestseller: true,
    rating: 4.9,
    reviews: 156,
    colors: ["Camel", "Black", "Navy"],
    images: [
      "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=800",
      "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800"
    ],
    inStock: true,
    stock: 12,
    isFeatured: true
  },
  {
    id: 2,
    name: "Silk Evening Gown",
    price: 3499,
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800",
    mainCategory: "womens",
    subCategories: ["dresses", "evening"],
    description: "Floor-length silk charmeuse gown with delicate draping and adjustable straps.",
    isNew: true,
    isBestseller: false,
    rating: 5.0,
    reviews: 89,
    colors: ["Champagne", "Emerald", "Ruby"],
    inStock: true,
    stock: 8,
    isFeatured: true
  },
  {
    id: 3,
    name: "Tailored Blazer",
    price: 1299,
    image: "https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=800",
    mainCategory: "womens",
    subCategories: ["blazers", "workwear"],
    description: "Impeccably tailored wool blazer with peak lapels and structured shoulders.",
    isNew: false,
    isBestseller: true,
    rating: 4.8,
    reviews: 234,
    colors: ["Black", "Ivory", "Charcoal"],
    inStock: true,
    stock: 24,
    isFeatured: false
  },
  {
    id: 4,
    name: "Pleated Midi Skirt",
    price: 799,
    image: "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=800",
    mainCategory: "womens",
    subCategories: ["skirts", "workwear"],
    description: "Elegant pleated midi skirt in premium Italian wool blend.",
    isNew: false,
    isBestseller: false,
    rating: 4.6,
    reviews: 112,
    colors: ["Navy", "Black", "Burgundy"],
    inStock: true,
    stock: 18,
    isFeatured: false
  },
  {
    id: 5,
    name: "Leather Trench Coat",
    price: 4299,
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800",
    mainCategory: "womens",
    subCategories: ["outerwear", "leather"],
    description: "Butter-soft lambskin leather trench coat with classic double-breasted silhouette.",
    isNew: true,
    isBestseller: true,
    rating: 5.0,
    reviews: 67,
    colors: ["Black", "Cognac"],
    inStock: true,
    stock: 6,
    isFeatured: true
  },
  {
    id: 6,
    name: "Merino Wool Sweater",
    price: 599,
    image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800",
    mainCategory: "womens",
    subCategories: ["knitwear", "sweaters"],
    description: "Luxuriously soft merino wool crewneck sweater with ribbed trim.",
    isNew: false,
    isBestseller: true,
    rating: 4.7,
    reviews: 189,
    colors: ["Cream", "Charcoal", "Dusty Rose"],
    inStock: true,
    stock: 32,
    isFeatured: false
  },
  {
    id: 7,
    name: "Wide-Leg Trousers",
    price: 899,
    image: "https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800",
    mainCategory: "womens",
    subCategories: ["trousers", "workwear"],
    description: "High-waisted wide-leg trousers in luxe wool crepe with pressed crease.",
    isNew: false,
    isBestseller: false,
    rating: 4.5,
    reviews: 143,
    colors: ["Black", "Navy", "Taupe"],
    inStock: true,
    stock: 20,
    isFeatured: false
  },
  {
    id: 8,
    name: "Satin Blouse",
    price: 649,
    image: "https://images.unsplash.com/photo-1618932260643-eee4a2f652a6?w=800",
    mainCategory: "womens",
    subCategories: ["tops", "blouses"],
    description: "Elegant satin blouse with French cuffs and mother-of-pearl buttons.",
    isNew: true,
    isBestseller: false,
    rating: 4.8,
    reviews: 98,
    colors: ["Ivory", "Black", "Blush"],
    inStock: true,
    stock: 16,
    isFeatured: false
  },

  // Men's Collection
  {
    id: 9,
    name: "Cashmere Overcoat",
    price: 3299,
    image: "https://images.unsplash.com/photo-1539533113208-f6df8cc8b543?w=800",
    mainCategory: "mens",
    subCategories: ["outerwear", "coats"],
    description: "Classic double-breasted overcoat in pure cashmere with notch lapels.",
    isNew: true,
    isBestseller: true,
    rating: 4.9,
    reviews: 178,
    colors: ["Charcoal", "Navy", "Camel"],
    inStock: true,
    stock: 14,
    isFeatured: true
  },
  {
    id: 10,
    name: "Three-Piece Suit",
    price: 2499,
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800",
    mainCategory: "mens",
    subCategories: ["suits", "formalwear"],
    description: "Impeccably tailored three-piece suit in Super 150s Italian wool.",
    isNew: false,
    isBestseller: true,
    rating: 5.0,
    reviews: 212,
    colors: ["Navy", "Charcoal", "Black"],
    inStock: true,
    stock: 18,
    isFeatured: true
  },
  {
    id: 11,
    name: "Oxford Dress Shirt",
    price: 349,
    image: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800",
    mainCategory: "mens",
    subCategories: ["shirts", "dress shirts"],
    description: "Classic Oxford cotton dress shirt with button-down collar.",
    isNew: false,
    isBestseller: true,
    rating: 4.7,
    reviews: 301,
    colors: ["White", "Light Blue", "Pink"],
    inStock: true,
    stock: 45,
    isFeatured: false
  },
  {
    id: 12,
    name: "Leather Bomber Jacket",
    price: 1899,
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800",
    mainCategory: "mens",
    subCategories: ["outerwear", "jackets", "leather"],
    description: "Premium lambskin leather bomber jacket with ribbed collar and cuffs.",
    isNew: true,
    isBestseller: false,
    rating: 4.8,
    reviews: 134,
    colors: ["Black", "Brown"],
    inStock: true,
    stock: 10,
    isFeatured: true
  },
  {
    id: 13,
    name: "Cashmere Turtleneck",
    price: 799,
    image: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800",
    mainCategory: "mens",
    subCategories: ["knitwear", "sweaters"],
    description: "Luxurious cashmere turtleneck in timeless silhouette.",
    isNew: false,
    isBestseller: false,
    rating: 4.6,
    reviews: 87,
    colors: ["Black", "Navy", "Camel"],
    inStock: true,
    stock: 22,
    isFeatured: false
  },
  {
    id: 14,
    name: "Wool Dress Trousers",
    price: 599,
    image: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800",
    mainCategory: "mens",
    subCategories: ["trousers", "formalwear"],
    description: "Perfectly pressed wool dress trousers with classic fit.",
    isNew: false,
    isBestseller: true,
    rating: 4.7,
    reviews: 165,
    colors: ["Navy", "Charcoal", "Black"],
    inStock: true,
    stock: 28,
    isFeatured: false
  },
  {
    id: 15,
    name: "Polo Sweater",
    price: 549,
    image: "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800",
    mainCategory: "mens",
    subCategories: ["knitwear", "casual"],
    description: "Fine merino wool polo sweater with contrast tipping.",
    isNew: true,
    isBestseller: false,
    rating: 4.5,
    reviews: 76,
    colors: ["Navy", "Grey", "Forest"],
    inStock: true,
    stock: 19,
    isFeatured: false
  },

  // Shoes Collection
  {
    id: 16,
    name: "Patent Leather Pumps",
    price: 899,
    image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800",
    mainCategory: "shoes",
    subCategories: ["womens", "heels", "pumps"],
    description: "Classic pointed-toe pumps in glossy patent leather with 3.5-inch heel.",
    isNew: false,
    isBestseller: true,
    rating: 4.8,
    reviews: 245,
    colors: ["Black", "Nude", "Red"],
    inStock: true,
    stock: 34,
    isFeatured: false
  },
  {
    id: 17,
    name: "Oxford Brogues",
    price: 1299,
    image: "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=800",
    mainCategory: "shoes",
    subCategories: ["mens", "dress shoes", "oxfords"],
    description: "Handcrafted full-brogue Oxfords in finest calfskin leather.",
    isNew: false,
    isBestseller: true,
    rating: 4.9,
    reviews: 198,
    colors: ["Black", "Brown"],
    inStock: true,
    stock: 26,
    isFeatured: true
  },
  {
    id: 18,
    name: "Suede Ankle Boots",
    price: 1599,
    image: "https://images.unsplash.com/photo-1605812860427-4024433a70fd?w=800",
    mainCategory: "shoes",
    subCategories: ["womens", "boots"],
    description: "Elegant suede ankle boots with stacked heel and almond toe.",
    isNew: true,
    isBestseller: false,
    rating: 4.7,
    reviews: 112,
    colors: ["Black", "Taupe", "Burgundy"],
    inStock: true,
    stock: 18,
    isFeatured: false
  },
  {
    id: 19,
    name: "Leather Loafers",
    price: 899,
    image: "https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=800",
    mainCategory: "shoes",
    subCategories: ["mens", "casual", "loafers"],
    description: "Timeless penny loafers in supple Italian leather.",
    isNew: false,
    isBestseller: true,
    rating: 4.6,
    reviews: 156,
    colors: ["Black", "Brown", "Burgundy"],
    inStock: true,
    stock: 31,
    isFeatured: false
  },
  {
    id: 20,
    name: "Strappy Sandals",
    price: 749,
    image: "https://images.unsplash.com/photo-1562183241-b937e95585b6?w=800",
    mainCategory: "shoes",
    subCategories: ["womens", "sandals", "heels"],
    description: "Delicate strappy sandals with metallic finish and slim heel.",
    isNew: true,
    isBestseller: false,
    rating: 4.5,
    reviews: 89,
    colors: ["Gold", "Silver", "Rose Gold"],
    inStock: true,
    stock: 15,
    isFeatured: false
  },

  // Accessories Collection
  {
    id: 21,
    name: "Leather Tote Bag",
    price: 1899,
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800",
    mainCategory: "accessories",
    subCategories: ["bags", "totes"],
    description: "Spacious leather tote with interior pockets and adjustable handles.",
    isNew: false,
    isBestseller: true,
    rating: 4.9,
    reviews: 267,
    colors: ["Black", "Cognac", "Navy"],
    inStock: true,
    stock: 22,
    isFeatured: true
  },
  {
    id: 22,
    name: "Silk Scarf",
    price: 299,
    image: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=800",
    mainCategory: "accessories",
    subCategories: ["scarves", "silk"],
    description: "Hand-rolled silk twill scarf with timeless pattern.",
    isNew: false,
    isBestseller: false,
    rating: 4.7,
    reviews: 134,
    colors: ["Multi", "Navy", "Burgundy"],
    inStock: true,
    stock: 42,
    isFeatured: false
  },
  {
    id: 23,
    name: "Leather Belt",
    price: 449,
    image: "https://images.unsplash.com/photo-1624222247344-550fb60583c2?w=800",
    mainCategory: "accessories",
    subCategories: ["belts", "leather"],
    description: "Classic leather belt with gold-tone buckle.",
    isNew: false,
    isBestseller: true,
    rating: 4.6,
    reviews: 178,
    colors: ["Black", "Brown"],
    inStock: true,
    stock: 38,
    isFeatured: false
  },
  {
    id: 24,
    name: "Cashmere Scarf",
    price: 599,
    image: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=800",
    mainCategory: "accessories",
    subCategories: ["scarves", "cashmere"],
    description: "Ultra-soft cashmere scarf with frayed edges.",
    isNew: true,
    isBestseller: false,
    rating: 4.8,
    reviews: 92,
    colors: ["Camel", "Grey", "Black"],
    inStock: true,
    stock: 27,
    isFeatured: false
  },
  {
    id: 25,
    name: "Structured Handbag",
    price: 2499,
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800",
    mainCategory: "accessories",
    subCategories: ["bags", "handbags"],
    description: "Architectural leather handbag with top handle and crossbody strap.",
    isNew: true,
    isBestseller: true,
    rating: 5.0,
    reviews: 156,
    colors: ["Black", "Ivory", "Burgundy"],
    inStock: true,
    stock: 11,
    isFeatured: true
  },

  // Jewelry Collection
  {
    id: 26,
    name: "Diamond Solitaire Necklace",
    price: 3999,
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800",
    mainCategory: "jewelry",
    subCategories: ["necklaces", "diamonds"],
    description: "Brilliant-cut diamond solitaire on delicate 18k gold chain.",
    isNew: true,
    isBestseller: true,
    rating: 5.0,
    reviews: 89,
    colors: ["White Gold", "Yellow Gold", "Rose Gold"],
    inStock: true,
    stock: 8,
    isFeatured: true
  },
  {
    id: 27,
    name: "Pearl Stud Earrings",
    price: 899,
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800",
    mainCategory: "jewelry",
    subCategories: ["earrings", "pearls"],
    description: "Classic Akoya pearl studs with 14k gold posts.",
    isNew: false,
    isBestseller: true,
    rating: 4.9,
    reviews: 234,
    colors: ["White Gold", "Yellow Gold"],
    inStock: true,
    stock: 24,
    isFeatured: false
  },
  {
    id: 28,
    name: "Gold Bangle Bracelet",
    price: 1299,
    image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800",
    mainCategory: "jewelry",
    subCategories: ["bracelets", "gold"],
    description: "Sculptural 18k gold bangle with polished finish.",
    isNew: false,
    isBestseller: false,
    rating: 4.7,
    reviews: 76,
    colors: ["Yellow Gold", "Rose Gold"],
    inStock: true,
    stock: 15,
    isFeatured: false
  },
  {
    id: 29,
    name: "Tennis Bracelet",
    price: 4999,
    image: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=800",
    mainCategory: "jewelry",
    subCategories: ["bracelets", "diamonds"],
    description: "Classic diamond tennis bracelet in platinum setting.",
    isNew: true,
    isBestseller: true,
    rating: 5.0,
    reviews: 112,
    colors: ["Platinum", "White Gold"],
    inStock: true,
    stock: 6,
    isFeatured: true
  },
  {
    id: 30,
    name: "Cocktail Ring",
    price: 2299,
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800",
    mainCategory: "jewelry",
    subCategories: ["rings", "statement"],
    description: "Bold cocktail ring with semi-precious stones in gold setting.",
    isNew: false,
    isBestseller: false,
    rating: 4.6,
    reviews: 67,
    colors: ["Yellow Gold", "Rose Gold"],
    inStock: true,
    stock: 12,
    isFeatured: false
  },

  // Kids Collection
  {
    id: 31,
    name: "Kids Cashmere Cardigan",
    price: 399,
    image: "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=800",
    mainCategory: "kids",
    subCategories: ["knitwear", "sweaters"],
    description: "Soft cashmere cardigan with pearl button closure.",
    isNew: true,
    isBestseller: false,
    rating: 4.8,
    reviews: 45,
    colors: ["Cream", "Pink", "Navy"],
    inStock: true,
    stock: 18,
    isFeatured: false
  },
  {
    id: 32,
    name: "Kids Wool Peacoat",
    price: 599,
    image: "https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=800",
    mainCategory: "kids",
    subCategories: ["outerwear", "coats"],
    description: "Classic double-breasted peacoat in premium wool blend.",
    isNew: false,
    isBestseller: true,
    rating: 4.7,
    reviews: 89,
    colors: ["Navy", "Red", "Camel"],
    inStock: true,
    stock: 22,
    isFeatured: false
  },
  {
    id: 33,
    name: "Kids Leather Shoes",
    price: 349,
    image: "https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=800",
    mainCategory: "kids",
    subCategories: ["shoes", "dress shoes"],
    description: "Polished leather dress shoes with cushioned insole.",
    isNew: false,
    isBestseller: false,
    rating: 4.5,
    reviews: 56,
    colors: ["Black", "Brown"],
    inStock: true,
    stock: 28,
    isFeatured: false
  },

  // Additional Featured Items
  {
    id: 34,
    name: "Luxury Watch",
    price: 8999,
    image: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=800",
    mainCategory: "accessories",
    subCategories: ["watches", "luxury"],
    description: "Swiss-made automatic watch with leather strap and sapphire crystal.",
    isNew: true,
    isBestseller: true,
    rating: 5.0,
    reviews: 167,
    colors: ["Silver", "Gold", "Rose Gold"],
    inStock: true,
    stock: 5,
    isFeatured: true
  },
  {
    id: 35,
    name: "Designer Sunglasses",
    price: 599,
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800",
    mainCategory: "accessories",
    subCategories: ["sunglasses", "eyewear"],
    description: "Iconic oversized sunglasses with UV protection and gold accents.",
    isNew: false,
    isBestseller: true,
    rating: 4.7,
    reviews: 201,
    colors: ["Black", "Tortoise", "Nude"],
    inStock: true,
    stock: 36,
    isFeatured: false
  }
];



// Example filter sections
export const filterSections = [
  {
    id: "price",
    title: "Price Range",
    type: "slider" as const,
    min: 0,
    max: 10000,
    step: 100,
    value: [0, 10000],
  },
  {
    id: "category",
    title: "Category",
    type: "checkbox" as const,
    options: [
      { id: "all", label: "All" },
      { id: "outerwear", label: "Outerwear" },
      { id: "accessories", label: "Accessories" },
      { id: "jewelry", label: "Jewelry" },
      { id: "beauty", label: "Beauty" },
    ],
  },
  {
    id: "rating",
    title: "Minimum Rating",
    type: "checkbox" as const,
    options: [
      { id: "5stars", label: "5+ Stars" },
      { id: "4stars", label: "4+ Stars" },
      { id: "3stars", label: "3+ Stars" },
    ],
  },
];